###Commodities
names_commodities <- rbind(
  c('Products of agriculture, Hunting, and Fishing','cagr'),
  c('Products of Forestry ','cfor'),
  c('Food products and beverages','cfoo'),
  c('Motor vehicles, trailers and semi-trailers','cveh'),
  c('Non-metallic minerals','cgla'),
  c('Paper and paperboard','cpap'),
  c('Chemicals','cche'),
  c('Plastics products','cpla'),
  c('Metals','cmet'),
  c('Other goods for industry','cigo'),
  c('Other goods for consumers','ccgo'),
  c('Construction and construction works','ccon'),
  c('Rail transport','crai'),
  c('Road transport','croa'),
  c('Water transport','cwat'),
  c('Air transport','cair'),
  c('Business services','cpri'),
  c('Public services','cpub'),
  c('Non-energy mining','cmin'),
  c('Coal and coal products','ccoa'),
  c('Crude oil','ccoi'),
  c('Transport fuels','cfut'),
  c('Heating fuel','cfuh'),
  c('Raw natural gas','crga'),
  c('Distributed natural gas','cdga'),
  c('Electricity','cele'),
  c('Heat','chea'),
  c('Biomass','cbio'),
  c('Other energy','cote'),
  c('Agriculture','C001'),
  c('Energy intensive industry','C002'),
  c('Other industry','C003'),
  c('Construction','C004'),
  c('Transport','C005'),
  c('Services','C006'),
  c('Fossil based energy','C007'),
  c('Other energy','C008')
) %>%
  as.data.frame() %>% rename(name = V1,code = V2)

names_sectors <- rbind(
  c('Agriculture and fishing','sagr'),
  c('Forestry','sfor'),
  c('Manufacture of food products and beverages','sfoo'),
  c('Manufacture of motor vehicles, trailers and semi-trailers','sveh'),
  c('Manufacture of non-metallic mineral products','sgla'),
  c('Manufacture of paper and paperboard','spap'),
  c('Manufacture of chemicals','sche'),
  c('Manufacture of plastics products','spla'),
  c('Metallurgy','smet'),
  c('Manufacture of other goods for industry','sigo'),
  c('Manufacture of other goods for consumers','scgo'),
  c('Construction of buildings and Civil engineering','scon'),
  c('Rail transport','srai'),
  c('Road transport','sroa'),
  c('Water transport','swat'),
  c('Air transport','sair'),
  c('Business services','spri'),
  c('Public services','spub'),
  c('Mining','smin'),
  c('Production of refined oil','soil'),
  c('Production of biofuel','sbfu'),
  c('Extraction of natural gas and Production of manufactured gas','spga'),
  c('Distribution of gas','sdga'),
  c('Production and distribution of biogas','sbga'),
  c('Nuclear electricity generation','senu'),
  c('Oil-fired electricity generation','seoi'),
  c('Gas-fired electricity generation','sega'),
  c('Coal-fired electricity generation','seco'),
  c('Wind electricity generation','sewi'),
  c('Solar electricity generation','seso'),
  c('Hydroelectric electricity generation','sehy'),
  c('Cogeneration (CHP) electricity generation and other heat supply','sech'),
  c('Electricity - Others','seot'),
  c('Agriculture','S001'),
  c('Energy intensive industry','S002'),
  c('Other industry','S003'),
  c('Construction','S004'),
  c('Transport','S005'),
  c('Services','S006'),
  c('Fossil based energy','S007'),
  c('Other energy','S008')
) %>%
  as.data.frame() %>% rename(name = V1,code = V2)
